// noinspection JSUnresolvedFunction
const IMAGES = {
  "FC_Cologne_logo.svg": require("../assets/crests/FC_Cologne_logo.png"),
  "Logo_TSG_Hoffenheim.svg": require("../assets/crests/Logo_TSG_Hoffenheim.png"),
  "Bayer_04_Leverkusen_logo.svg": require("../assets/crests/Bayer_04_Leverkusen_logo.png"),
  "FC_Bayern_Munchen_logo_(2017).svg": require("../assets/crests/FC_Bayern_Munchen_logo_(2017).png"),
  "FC_Schalke_04_Logo.svg": require("../assets/crests/FC_Schalke_04_Logo.png"),
  "HSV-Logo.svg": require("../assets/crests/HSV-Logo.png"),
  "Hannover_96_Logo.svg": require("../assets/crests/Hannover_96_Logo.png"),
  "Hertha_BSC_Logo_2012.svg": require("../assets/crests/Hertha_BSC_Logo_2012.png"),
  "Logo-VfL-Wolfsburg.svg": require("../assets/crests/Logo-VfL-Wolfsburg.png"),
  "SV-Werder-Bremen-Logo.svg": require("../assets/crests/SV-Werder-Bremen-Logo.png"),
  "Logo_1_FC_Kaiserslautern.svg": require("../assets/crests/Logo_1_FC_Kaiserslautern.png"),
  "1._FC_Nurnberg_logo.svg": require("../assets/crests/1._FC_Nurnberg_logo.png"),
  "FSV_Mainz_05.svg": require("../assets/crests/FSV_Mainz_05.png"),
  "Logo_FC_Augsburg.svg": require("../assets/crests/Logo_FC_Augsburg.png"),
  "SC-Freiburg_Logo-neu.svg": require("../assets/crests/SC-Freiburg_Logo-neu.png"),
  "Borussia_Monchengladbach_logo.svg": require("../assets/crests/Borussia_Monchengladbach_logo.png"),
  "Eintracht_Frankfurt_Logo.svg": require("../assets/crests/Eintracht_Frankfurt_Logo.png"),
  "SpVgg_Greuther_Furth_logo.svg": require("../assets/crests/SpVgg_Greuther_Furth_logo.png"),
  "Fc_erzgebirge_aue.svg": require("../assets/crests/Fc_erzgebirge_aue.png"),
  "Fcenergie.png": require("../assets/crests/Fcenergie.png"),
  "Fortuna_Dusseldorf.svg": require("../assets/crests/Fortuna_Dusseldorf.png"),
  "TSV_1860_Munchen.svg": require("../assets/crests/TSV_1860_Munchen.png"),
  "SC_Paderborn_07_Logo.svg": require("../assets/crests/SC_Paderborn_07_Logo.png"),
  "FSV_Frankfurt_1899.svg": require("../assets/crests/FSV_Frankfurt_1899.png"),
  "FC-Ingolstadt_logo.svg": require("../assets/crests/FC-Ingolstadt_logo.png"),
// "Karlsruher_SC_Logo.svg"://   require("./../assets/crests/Karlsruher_SC_Logo.png"),
  "Logo_Eintracht_Braunschweig.svg": require("../assets/crests/Logo_Eintracht_Braunschweig.png"),
// "FC_Hansa_Rostock.png"://   require("./../assets/crests/FC_Hansa_Rostock.png"),
  "Logo_SG_Dynamo_Dresden_neu.svg": require("../assets/crests/Logo_SG_Dynamo_Dresden_neu.png"),
  "VfL_Bochum_logo.svg": require("../assets/crests/VfL_Bochum_logo.png"),
  "Logo_Arminia_Bielefeld.svg": require("../assets/crests/Logo_Arminia_Bielefeld.png"),
  "Logo_SV_Wehen_Wiesbaden.svg": require("../assets/crests/Logo_SV_Wehen_Wiesbaden.png"),
  "Rot_Weiss_Erfurt_Logo.svg": require("../assets/crests/Rot_Weiss_Erfurt_Logo.png"),
  "1._FC_Saarbrucken.svg": require("../assets/crests/1._FC_Saarbrucken.png"),
// "Jahn_Regensburg_logo2014.png"://   require("./../assets/crests/Jahn_Regensburg_logo2014.png"),
  "1._FC_Heidenheim_1846.svg": require("../assets/crests/1._FC_Heidenheim_1846.png"),
  "VfB_Stuttgart_Logo.svg": require("../assets/crests/VfB_Stuttgart_Logo.png"),
  "SV_Sandhausen.svg": require("../assets/crests/SV_Sandhausen.png"),
  "SpVgg_Unterhaching_Logo_2012.svg": require("../assets/crests/SpVgg_Unterhaching_Logo_2012.png"),
  "VfR_Aalen_Wappen.svg": require("../assets/crests/VfR_Aalen_Wappen.png"),
  "Chelsea_crest.svg": require("../assets/crests/Chelsea_crest.png"),
  "Everton_FC.svg": require("../assets/crests/Everton_FC.png"),
  "Fulham_fc.svg": require("../assets/crests/Fulham_fc.png"),
  "FC_Liverpool.svg": require("../assets/crests/FC_Liverpool.png"),
  "Manchester_City_FC_badge.svg": require("../assets/crests/Manchester_City_FC_badge.png"),
  "Manchester_United_FC.svg": require("../assets/crests/Manchester_United_FC.png"),
  "Newcastle_United_Logo.svg": require("../assets/crests/Newcastle_United_Logo.png"),
  "Norwich_City.svg": require("../assets/crests/Norwich_City.png"),
  "Queens_Park_Rangers.svg": require("../assets/crests/Queens_Park_Rangers.png"),
  "Stoke_City.svg": require("../assets/crests/Stoke_City.png"),
  "AFC_Sunderland.svg": require("../assets/crests/AFC_Sunderland.png"),
  "Swansea_City_Logo.svg": require("../assets/crests/Swansea_City_Logo.png"),
  "Tottenham_Hotspur.svg": require("../assets/crests/Tottenham_Hotspur.png"),
  "West_Bromwich_Albion.svg": require("../assets/crests/West_Bromwich_Albion.png"),
  "Wigan_Athletic.svg": require("../assets/crests/Wigan_Athletic.png"),
  "Athletic_Club_Bilbao.svg": require("../assets/crests/Athletic_Club_Bilbao.png"),
  "Atletico_Madrid_logo.svg": require("../assets/crests/Atletico_Madrid_logo.png"),
  "Atletico_Osasuna.svg": require("../assets/crests/Atletico_Osasuna.png"),
  "RCD_Espanyol_De_Barcelona.svg": require("../assets/crests/RCD_Espanyol_De_Barcelona.png"),
  "Fc_barcelona.svg": require("../assets/crests/Fc_barcelona.png"),
  "Getafe_CF.svg": require("../assets/crests/Getafe_CF.png"),
  "Granada_CF.svg": require("../assets/crests/Granada_CF.png"),
  "FC_Malaga.svg": require("../assets/crests/FC_Malaga.png"),
  "Real_Madrid_Logo.svg": require("../assets/crests/Real_Madrid_Logo.png"),
  "Rayo_vallecano_madrid.svg": require("../assets/crests/Rayo_vallecano_madrid.png"),
  "Levante_ud.svg": require("../assets/crests/Levante_ud.png"),
  "Rcd_mallorca.svg": require("../assets/crests/Rcd_mallorca.png"),
  "Real_Betis.svg": require("../assets/crests/Real_Betis.png"),
  "Real_zaragoza.svg": require("../assets/crests/Real_zaragoza.png"),
  "Real_Sociedad_San_Sebastian.svg": require("../assets/crests/Real_Sociedad_San_Sebastian.png"),
  "Villarreal_CF_logo.svg": require("../assets/crests/Villarreal_CF_logo.png"),
  "FC_Valencia.svg": require("../assets/crests/FC_Valencia.png"),
  "Real_Sporting_de_Gijon.svg": require("../assets/crests/Real_Sporting_de_Gijon.png"),
  "AC_Mailand_Logo.svg": require("../assets/crests/AC_Mailand_Logo.png"),
  "ACF_Fiorentina_2.svg": require("../assets/crests/ACF_Fiorentina_2.png"),
  "AS_Rom.svg": require("../assets/crests/AS_Rom.png"),
  "AC_Siena.svg": require("../assets/crests/AC_Siena.png"),
  "Atalanta_BC.svg": require("../assets/crests/Atalanta_BC.png"),
  "FC_Bologna.svg": require("../assets/crests/FC_Bologna.png"),
  "Cagliari_Calcio.svg": require("../assets/crests/Cagliari_Calcio.png"),
  "AC_Chievo_Verona.svg": require("../assets/crests/AC_Chievo_Verona.png"),
  "Genoa_CFC.svg": require("../assets/crests/Genoa_CFC.png"),
// "Logo_FC_Internazionale_Milano_2014.png"://   require("./../assets/crests/Logo_FC_Internazionale_Milano_2014.png"),
  "Juventus_Turin.svg": require("../assets/crests/Juventus_Turin.png"),
// "500px-Lazio_Rom.svg.png"://   require("./../assets/crests/500px-Lazio_Rom.png"),
// "Stuttgarter_Kickers.png"://   require("./../assets/crests/Stuttgarter_Kickers.png"),
// "SC_Fortuna_Koln.png"://   require("./../assets/crests/SC_Fortuna_Koln.png"),
  "Albacete_balompie.svg": require("../assets/crests/Albacete_balompie.png"),
  "Real_Valladolid_Logo.svg": require("../assets/crests/Real_Valladolid_Logo.png"),
  "CD_Tenerife_Logo.svg": require("../assets/crests/CD_Tenerife_Logo.png"),
  "Real_Murcia.svg": require("../assets/crests/Real_Murcia.png"),
  "CD_Numancia_logo.svg": require("../assets/crests/CD_Numancia_logo.png"),
  "Deportivo_Alaves_logo.svg": require("../assets/crests/Deportivo_Alaves_logo.png"),
  "Cadiz_CF_logo.svg": require("../assets/crests/Cadiz_CF_logo.png"),
// "Gimnastic_tarragona_200px.png"://   require("./../assets/crests/Gimnastic_tarragona_200px.png"),
// "Recreativo_Huelva_logo.svg"://   require("./../assets/crests/Recreativo_Huelva_logo.png"),
  "Union_Deportiva_Almeria.svg": require("../assets/crests/Union_Deportiva_Almeria.png"),
// "Hercules_cf_200px.png"://   require("./../assets/crests/Hercules_cf_200px.png"),
  "Logrones_CF.svg": require("../assets/crests/Logrones_CF.png"),
  "SD_Eibar_logo.svg": require("../assets/crests/SD_Eibar_logo.png"),
  "Elche_CF.svg": require("../assets/crests/Elche_CF.png"),
  "SD_Ponferradina_logo.svg": require("../assets/crests/SD_Ponferradina_logo.png"),
  "Real_Madrid_CF.svg": require("../assets/crests/Real_Madrid_CF.png"),
  "Cordoba_CF_logo.svg": require("../assets/crests/Cordoba_CF_logo.png"),
  "For_article_Girona_FC.svg": require("../assets/crests/For_article_Girona_FC.png"),
  "Sd_huesca.png": require("../assets/crests/Sd_huesca.png"),
// "FCB.svg"://   require("./../assets/crests/FCB.png"),
  "AD_Alcorcon_logo.svg": require("../assets/crests/AD_Alcorcon_logo.png"),
  "Birmingham_City_FC_logo.svg": require("../assets/crests/Birmingham_City_FC_logo.png"),
  "Blackpool_FC_logo.svg": require("../assets/crests/Blackpool_FC_logo.png"),
  "Leicester02.png": require("../assets/crests/Leicester02.png"),
  "FC_Southampton.svg": require("../assets/crests/FC_Southampton.png"),
  "Derby_County_crest.svg": require("../assets/crests/Derby_County_crest.png"),
  "Middlesbrough_FC_crest.svg": require("../assets/crests/Middlesbrough_FC_crest.png"),
// "Sheffield_Wednesday_crest_from_2016.jpg"://   require("./../assets/crests/Sheffield_Wednesday_crest_from_2016.jpg"),
  "Watford.svg": require("../assets/crests/Watford.png"),
  "Ipswich_Town.svg": require("../assets/crests/Ipswich_Town.png"),
  "Nottingham_Forest_logo.svg": require("../assets/crests/Nottingham_Forest_logo.png"),
  "Crystal_Palace_F.C._logo_(2013).png": require("../assets/crests/Crystal_Palace_F.C._logo_(2013).png"),
  "Sheffield_United_FC_logo.svg": require("../assets/crests/Sheffield_United_FC_logo.png"),
  "Barnsley_FC.svg": require("../assets/crests/Barnsley_FC.png"),
  "Rochdale_badge.png": require("../assets/crests/Rochdale_badge.png"),
  "Chesterfield_FC_crest.svg": require("../assets/crests/Chesterfield_FC_crest.png"),
  "Colchester_United_FC_logo.svg": require("../assets/crests/Colchester_United_FC_logo.png"),
  "Walsall_FC.svg": require("../assets/crests/Walsall_FC.png"),
// "788px-FC_Gillingham_Logo.svg.png"://   require("./../assets/crests/788px-FC_Gillingham_Logo.png"),
// "Port_Vale_logo.svg"://   require("./../assets/crests/Port_Vale_logo.png"),
  "Huddersfield_Town_A.F.C._logo.svg": require("../assets/crests/Huddersfield_Town_A.F.C._logo.png"),
// "Brighton_&_Hove_Albion_logo.svg"://   require("./../assets/crests/Brighton_ & _Hove_Albion_logo.png"),
  "AS_Bari.svg": require("../assets/crests/AS_Bari.png"),
// "AS_Livorno.svg"://   require("./../assets/crests/AS_Livorno.png"),
  "Reggina_Calcio.svg": require("../assets/crests/Reggina_Calcio.png"),
  "Logo_FC_Empoli.svg": require("../assets/crests/Logo_FC_Empoli.png"),
  "Brescia_Calcio.svg": require("../assets/crests/Brescia_Calcio.png"),
  "Hellas_Verona_1903_FC.svg": require("../assets/crests/Hellas_Verona_1903_FC.png"),
  "Calcio_Padova.svg": require("../assets/crests/Calcio_Padova.png"),
  "AS_Cittadella.svg": require("../assets/crests/AS_Cittadella.png"),
  "Frosinonestemma.png": require("../assets/crests/Frosinonestemma.png"),
  "US_Sassuolo_Calcio.svg": require("../assets/crests/US_Sassuolo_Calcio.png"),
  "FC_Crotone.svg": require("../assets/crests/FC_Crotone.png"),
  "Ternana_Calcio.svg": require("../assets/crests/Ternana_Calcio.png"),
  "AS_Avellino.png": require("../assets/crests/AS_Avellino.png"),
  "Spezia_Calcio.svg": require("../assets/crests/Spezia_Calcio.png"),
  "Rio_Ave_FC.svg": require("../assets/crests/Rio_Ave_FC.png"),
  "Sporting_Clube_de_Braga.svg": require("../assets/crests/Sporting_Clube_de_Braga.png"),
// "Sporting_Clube_de_Portugal.png"://   require("./../assets/crests/Sporting_Clube_de_Portugal.png"),
  "SC_Olhanense_Logo.svg": require("../assets/crests/SC_Olhanense_Logo.png"),
  "Nacional_Funchal.svg": require("../assets/crests/Nacional_Funchal.png"),
  "Vitoria_Guimaraes.svg": require("../assets/crests/Vitoria_Guimaraes.png"),
  "FC_Porto_1922-2005.svg": require("../assets/crests/FC_Porto_1922-2005.png"),
  "Maritimo_Funchal.svg": require("../assets/crests/Maritimo_Funchal.png"),
  "Vitoria_Setubal.svg": require("../assets/crests/Vitoria_Setubal.png"),
  "FC_Pacos_de_Ferreira.svg": require("../assets/crests/FC_Pacos_de_Ferreira.png"),
  "Logo_Academica_de_Coimbra.svg": require("../assets/crests/Logo_Academica_de_Coimbra.png"),
  "AC_Ajaccio.svg": require("../assets/crests/AC_Ajaccio.png"),
  "FC_Toulouse_Logo.svg": require("../assets/crests/FC_Toulouse_Logo.png"),
  "Stade_Brestois_29.svg": require("../assets/crests/Stade_Brestois_29.png"),
  "Evian_Thonon_Gaillard.svg": require("../assets/crests/Evian_Thonon_Gaillard.png"),
  "LogoSmc2013.png": require("../assets/crests/LogoSmc2013.png"),
  "Valenciennes_AFC_(2008).svg": require("../assets/crests/Valenciennes_AFC_(2008).png"),
  "Olympique_Marseille_Logo.svg": require("../assets/crests/Olympique_Marseille_Logo.png"),
// "FC_Sochaux_Logo_2010.svg"://   require("./../assets/crests/FC_Sochaux_Logo_2010.png"),
  "HSC_Montpellier_Logo.svg": require("../assets/crests/HSC_Montpellier_Logo.png"),
  "AJ_Auxerre.svg": require("../assets/crests/AJ_Auxerre.png"),
  "AS_Nancy_Logo.svg": require("../assets/crests/AS_Nancy_Logo.png"),
  "LOSC_Lille_Crest_2012.png": require("../assets/crests/LOSC_Lille_Crest_2012.png"),
  "OGC_Nice_Logo.png": require("../assets/crests/OGC_Nice_Logo.png"),
  "Olympique_Lyon.svg": require("../assets/crests/Olympique_Lyon.png"),
  "Paris_Saint-Germain_Logo.svg": require("../assets/crests/Paris_Saint-Germain_Logo.png"),
  "FC_Lorient_neu.png": require("../assets/crests/FC_Lorient_neu.png"),
  "Girondins_Bordeaux_Logo.svg": require("../assets/crests/Girondins_Bordeaux_Logo.png"),
  "AS_Saint-Etienne_(aktuell).svg": require("../assets/crests/AS_Saint-Etienne_(aktuell).png"),
  "FCO_Dijon.svg": require("../assets/crests/FCO_Dijon.png"),
  "Stade_Rennais_Football_Club.svg": require("../assets/crests/Stade_Rennais_Football_Club.png"),
  "SC_Amiens_Logo.svg": require("../assets/crests/SC_Amiens_Logo.png"),
  "ES_Troyes_AC.svg": require("../assets/crests/ES_Troyes_AC.png"),
  "SCO_Angers.svg": require("../assets/crests/SCO_Angers.png"),
  "Le_Havre_AC.svg": require("../assets/crests/Le_Havre_AC.png"),
  "AC_Arles-Avignon_Logo.svg": require("../assets/crests/AC_Arles-Avignon_Logo.png"),
  "SC_Bastia.svg": require("../assets/crests/SC_Bastia.png"),
  "FC_Istres.svg": require("../assets/crests/FC_Istres.png"),
  "EA_Guingamp_Logo.svg": require("../assets/crests/EA_Guingamp_Logo.png"),
  "La_Berrichonne_de_Chateauroux.svg": require("../assets/crests/La_Berrichonne_de_Chateauroux.png"),
  "Stade_Laval.svg": require("../assets/crests/Stade_Laval.png"),
  "Clermont_Foot_Auvergne.svg": require("../assets/crests/Clermont_Foot_Auvergne.png"),
  "FC_Nantes_(seit_2008).svg": require("../assets/crests/FC_Nantes_(seit_2008).png"),
  "FC_Tours.svg": require("../assets/crests/FC_Tours.png"),
  "FC_Metz_Logo.svg": require("../assets/crests/FC_Metz_Logo.png"),
  "Borussia_Dortmund_logo.svg": require("../assets/crests/Borussia_Dortmund_logo.png"),
// "Hallescher_FC_Logo_2012.svg"://   require("./../assets/crests/Hallescher_FC_Logo_2012.png"),
// "Gazelec_Ajaccio_logo.png"://   require("./../assets/crests/Gazelec_Ajaccio_logo.png"),
  "Olympique_Nimes.svg": require("../assets/crests/Olympique_Nimes.png"),
  "Chamois_Niort_Logo.svg": require("../assets/crests/Chamois_Niort_Logo.png"),
  "Celta_Vigo.svg": require("../assets/crests/Celta_Vigo.png"),
  "Sevilla_cf_200px.png": require("../assets/crests/Sevilla_cf_200px.png"),
  "RC_Deportivo_La_Coruna_logo.svg": require("../assets/crests/RC_Deportivo_La_Coruna_logo.png"),
  "West_Ham_United_FC.svg": require("../assets/crests/West_Ham_United_FC.png"),
// "Logo_RedStarFC.png"://   require("./../assets/crests/Logo_RedStarFC.png"),
  "US_Creteil.svg": require("../assets/crests/US_Creteil.png"),
  "Racing_Club_Strasbourg.svg": require("../assets/crests/Racing_Club_Strasbourg.png"),
  "GD_Estoril_Praia.svg": require("../assets/crests/GD_Estoril_Praia.png"),
  "Logo_Moreirense.svg": require("../assets/crests/Logo_Moreirense.png"),
  "Sampdoria_badge.png": require("../assets/crests/Sampdoria_badge.png"),
  "Pescara_Calcio.svg": require("../assets/crests/Pescara_Calcio.png"),
  "Torino_FC_Logo.svg": require("../assets/crests/Torino_FC_Logo.png"),
  "Novara_Calcio.svg": require("../assets/crests/Novara_Calcio.png"),
  "SS_Juve_Stabia.svg": require("../assets/crests/SS_Juve_Stabia.png"),
  "Virtus_Lanciano.svg": require("../assets/crests/Virtus_Lanciano.png"),
  "AC_Cesena.svg": require("../assets/crests/AC_Cesena.png"),
  "CD_Mirandes_logo.svg": require("../assets/crests/CD_Mirandes_logo.png"),
  "CD_Lugo_logo.svg": require("../assets/crests/CD_Lugo_logo.png"),
  "Trabzonspor.svg": require("../assets/crests/Trabzonspor.png"),
  "Galatasaray_Sports_Club_Logo.png": require("../assets/crests/Galatasaray_Sports_Club_Logo.png"),
// "Qarabag,logo,2016.png"://   require("./../assets/crests/Qarabag, logo, 2016.png"),
  "AEK_F_C_.svg": require("../assets/crests/AEK_F_C_.png"),
  "Logo_Olympiakos_Piraus.svg": require("../assets/crests/Logo_Olympiakos_Piraus.png"),
  "Roda_JC_Kerkrade_(2011).svg": require("../assets/crests/Roda_JC_Kerkrade_(2011).png"),
  "FC_Twente_Enschede_(ab_2006).svg": require("../assets/crests/FC_Twente_Enschede_(ab_2006).png"),
  "NEC_Nijmegen.svg": require("../assets/crests/NEC_Nijmegen.png"),
  "VVV-Venlo_logo.svg": require("../assets/crests/VVV-Venlo_logo.png"),
// "Degraafschap.png"://   require("./../assets/crests/Degraafschap.png"),
  "SBV_Excelsior_logo.png": require("../assets/crests/SBV_Excelsior_logo.png"),
  "Heracles_Almelo.svg": require("../assets/crests/Heracles_Almelo.png"),
  "Willem_II_Tilburg.svg": require("../assets/crests/Willem_II_Tilburg.png"),
  "SC_Heerenveen.svg": require("../assets/crests/SC_Heerenveen.png"),
  "PSV_Eindhoven.svg": require("../assets/crests/PSV_Eindhoven.png"),
  "Logo_Feyenoord_Rotterdam.svg": require("../assets/crests/Logo_Feyenoord_Rotterdam.png"),
  "FC_Utrecht.svg": require("../assets/crests/FC_Utrecht.png"),
  "FC_Groningen.svg": require("../assets/crests/FC_Groningen.png"),
  "Ajax_Amsterdam.svg": require("../assets/crests/Ajax_Amsterdam.png"),
  "Vitesse_Arnheim.svg": require("../assets/crests/Vitesse_Arnheim.png"),
  "ADO_Den_Haag.svg": require("../assets/crests/ADO_Den_Haag.png"),
  "Logo_NAC_Breda.png": require("../assets/crests/Logo_NAC_Breda.png"),
  "AZ_Alkmaar.svg": require("../assets/crests/AZ_Alkmaar.png"),
  "RKC_Waalwijk_logo.png": require("../assets/crests/RKC_Waalwijk_logo.png"),
  "PEC_Zwolle_2012.svg": require("../assets/crests/PEC_Zwolle_2012.png"),
  "Real_Jaen.svg": require("../assets/crests/Real_Jaen.png"),
  "Belenenses_Lissabon.svg": require("../assets/crests/Belenenses_Lissabon.png"),
  "FC_Arouca.png": require("../assets/crests/FC_Arouca.png"),
  "Carpi_FC_1909_logo.png": require("../assets/crests/Carpi_FC_1909_logo.png"),
// "FC_Shakhtar_Donetsk.png"://   require("./../assets/crests/FC_Shakhtar_Donetsk.png"),
  "FC_Basel.png": require("../assets/crests/FC_Basel.png"),
  "FC_Zenit_1_star_2015_logo.png": require("../assets/crests/FC_Zenit_1_star_2015_logo.png"),
  "Celtic_FC.svg": require("../assets/crests/Celtic_FC.png"),
// "Nkmaribor_2013.png"://   require("./../assets/crests/Nkmaribor_2013.png"),
  "CABastia.gif": require("../assets/crests/CABastia.gif"),
// "FSV_Mainz_05_Logo.svg"://   require("./../assets/crests/FSV_Mainz_05_Logo.png"),
  "SG_Sonnenhof.svg": require("../assets/crests/SG_Sonnenhof.png"),
// "200px-Union_sportive_Orleans_Loiret_football_2.jpg"://   require("./../assets/crests/200px-Union_sportive_Orleans_Loiret_football_2.jpg"),
  "UE_Llagostera.png": require("../assets/crests/UE_Llagostera.png"),
// "180px-Club_Deportivo_Leganes.png"://   require("./../assets/crests/180px-Club_Deportivo_Leganes.png"),
// "125px-FC_Dordrecht.svg.png"://   require("./../assets/crests/125px-FC_Dordrecht.png"),
  "ACD_Virtus_Entella_logo.png": require("../assets/crests/ACD_Virtus_Entella_logo.png"),
// "150px-Logo_BATE_Baryssau.svg.png"://   require("./../assets/crests/150px-Logo_BATE_Baryssau.png"),
  "Logo_Malmo_FF.svg": require("../assets/crests/Logo_Malmo_FF.png"),
  "CSKA_Moscow_logo.png": require("../assets/crests/CSKA_Moscow_logo.png"),
  "APOELnew.png": require("../assets/crests/APOELnew.png"),
  "Ludogorets_FC.png": require("../assets/crests/Ludogorets_FC.png"),
  "FC_Spartak_Moscow_logo.png": require("../assets/crests/FC_Spartak_Moscow_logo.png"),
  "main-logo.png": require("../assets/crests/main-logo.png"),
  "Flag_of_Germany.svg": require("../assets/crests/Flag_of_Germany.png"),
  "Flag_of_Spain.svg": require("../assets/crests/Flag_of_Spain.png"),
  "Flag_of_Portugal.svg": require("../assets/crests/Flag_of_Portugal.png"),
  "Flag_of_Slovakia.svg": require("../assets/crests/Flag_of_Slovakia.png"),
  "Flag_of_England.svg": require("../assets/crests/Flag_of_England.png"),
  "Flag_of_France.svg": require("../assets/crests/Flag_of_France.png"),
  "Flag_of_Italy.svg": require("../assets/crests/Flag_of_Italy.png"),
  "Flag_of_Switzerland_(Pantone).svg": require("../assets/crests/Flag_of_Switzerland_(Pantone).png"),
  "Flag_of_Ukraine.svg": require("../assets/crests/Flag_of_Ukraine.png"),
  "Flag_of_Sweden.svg": require("../assets/crests/Flag_of_Sweden.png"),
  "Flag_of_Poland.svg": require("../assets/crests/Flag_of_Poland.png"),
  "Flag_of_the_Czech_Republic.svg": require("../assets/crests/Flag_of_the_Czech_Republic.png"),
  "Flag_of_Croatia.svg": require("../assets/crests/Flag_of_Croatia.png"),
  "Flag_of_Belgium.svg": require("../assets/crests/Flag_of_Belgium.png"),
  "Flag_of_Ireland.svg": require("../assets/crests/Flag_of_Ireland.png"),
  "Flag_of_Russia.svg": require("../assets/crests/Flag_of_Russia.png"),
  "F.C._Penafiel_logo.svg": require("../assets/crests/F.C._Penafiel_logo.png"),
  "Boavista_F.C._logo.svg": require("../assets/crests/Boavista_F.C._logo.png"),
  "Flag_of_Romania.svg": require("../assets/crests/Flag_of_Romania.png"),
  "Flag_of_Austria.svg": require("../assets/crests/Flag_of_Austria.png"),
  "Flag_of_Hungary.svg": require("../assets/crests/Flag_of_Hungary.png"),
  "Flag_of_Northern_Ireland.svg": require("../assets/crests/Flag_of_Northern_Ireland.png"),
  "Flag_of_Wales_2.svg": require("../assets/crests/Flag_of_Wales_2.png"),
  "FC_Dynamo_Kyiv_logo.png": require("../assets/crests/FC_Dynamo_Kyiv_logo.png"),
  "FC_Nordsjaelland.svg": require("../assets/crests/FC_Nordsjaelland.png"),
  "Debreceni_Vasutas_SC.svg": require("../assets/crests/Debreceni_Vasutas_SC.png"),
  "MTAFC_logo.png": require("../assets/crests/MTAFC_logo.png"),
// "Football_Bourg_en_Bresse_Peronnas_logo.png"://   require("./../assets/crests/Football_Bourg_en_Bresse_Peronnas_logo.png"),
  "Afc_bournemouth.svg": require("../assets/crests/Afc_bournemouth.png"),
  "Logo_ParisFC_2011.png": require("../assets/crests/Logo_ParisFC_2011.png"),
// "150px-Athletic_Club_Bilbao.svg.png"://   require("./../assets/crests/150px-Athletic_Club_Bilbao.png"),
  "Real_Oviedo.svg": require("../assets/crests/Real_Oviedo.png"),
  "Emblema_CD_Tondela.png": require("../assets/crests/Emblema_CD_Tondela.png"),
  "UMadeira.png": require("../assets/crests/UMadeira.png"),
  "Flag_of_Albania.svg": require("../assets/crests/Flag_of_Albania.png"),
  "Flag_of_Iceland.svg": require("../assets/crests/Flag_of_Iceland.png"),
  "Bradford_City_AFC.png": require("../assets/crests/Bradford_City_AFC.png"),
  "Bury_FC.svg": require("../assets/crests/Bury_FC.png"),
  "Southend_United.svg": require("../assets/crests/Southend_United.png"),
  "Doncaster_Rovers_FC.png": require("../assets/crests/Doncaster_Rovers_FC.png"),
// "847px-Burton_Albion_FC_logo.svg.png"://   require("./../assets/crests/847px-Burton_Albion_FC_logo.png"),
  "Fleetwood_Town_FC.png": require("../assets/crests/Fleetwood_Town_FC.png"),
  "Crewe_Alexandra.svg": require("../assets/crests/Crewe_Alexandra.png"),
  "Oldham_Athletic_new_badge.png": require("../assets/crests/Oldham_Athletic_new_badge.png"),
  "Coventry_City_FC_logo.svg": require("../assets/crests/Coventry_City_FC_logo.png"),
  "Peterborough_United.svg": require("../assets/crests/Peterborough_United.png"),
  "Scunthorpe_United_FC_logo.svg": require("../assets/crests/Scunthorpe_United_FC_logo.png"),
  "Swindon_Town_FC.svg": require("../assets/crests/Swindon_Town_FC.png"),
// "Shrewsbury_Town_Badge_2015-.jpg"://   require("./../assets/crests/Shrewsbury_Town_Badge_2015 -.jpg"),
  "Sparta_Rotterdam_logo.jpeg": require("../assets/crests/Sparta_Rotterdam_logo.jpeg"),
// "Fvrlogo.png"://   require("./../assets/crests/Fvrlogo.png"),
  "Cf_reus_deportiu_200.png": require("../assets/crests/Cf_reus_deportiu_200.png"),
  "G_D_Chaves.png": require("../assets/crests/G_D_Chaves.png"),
  "FC_Rostov_logo.png": require("../assets/crests/FC_Rostov_logo.png"),
  "Legia_Warszawa.svg": require("../assets/crests/Legia_Warszawa.png"),
  "Wycombe_Wanderers_FC_logo.svg": require("../assets/crests/Wycombe_Wanderers_FC_logo.png"),
  "Portimonense_Sporting_Clube.png": require("../assets/crests/Portimonense_Sporting_Clube.png"),
  "Flamengo_logo.svg": require("../assets/crests/Flamengo_logo.png"),
  "Arsenal_FC.svg": require("../assets/crests/Arsenal_FC.png"),
  "Burnley_FC_badge.png": require("../assets/crests/Burnley_FC_badge.png"),
  "UD_Las_Palmas_logo.svg": require("../assets/crests/UD_Las_Palmas_logo.png"),
  "S.S.C._Napoli_logo.svg": require("../assets/crests/S.S.C._Napoli_logo.png"),
  "Udinese_Calcio.svg": require("../assets/crests/Udinese_Calcio.png"),
  "Logo_Benfica_Lissabon.svg": require("../assets/crests/Logo_Benfica_Lissabon.png"),
  "Holstein_Kiel_Logo.svg": require("../assets/crests/Holstein_Kiel_Logo.png"),
  "Chemnitzer_FC_Logo.svg": require("../assets/crests/Chemnitzer_FC_Logo.png"),
// "Fortuna_Düsseldorf.svg"://    require("./../assets/crests/Fortuna_Düsseldorf.png"),
// "Svdarmstadt98.svg"://    require("./../assets/crests/Svdarmstadt98.png"),
// "Kickers_Wurzburg.png"://    require("./../assets/crests/Kickers_Wurzburg.png"),
  "RB_Leipzig_2014_logo.svg": require("../assets/crests/RB_Leipzig_2014_logo.png"),
  "Logo_Vfl_Osnabrueck.svg": require("../assets/crests/Logo_Vfl_Osnabrueck.png"),
// "SpVgg_Greuther_Fürth_logo.svg"://    require("./../assets/crests/SpVgg_Greuther_Fürth_logo.png"),
// "1_FC_Magdeburg.png"://    require("./../assets/crests/1_FC_Magdeburg.png"),
  "FC_Parma.svg": require("../assets/crests/FC_Parma.png"),
  "US_Palermo.svg": require("../assets/crests/US_Palermo.png"),
  "AS_Monaco.svg": require("../assets/crests/AS_Monaco.png"),
  "Millwall_FC_logo.png": require("../assets/crests/Millwall_FC_logo.png"),
// "Cardiff_City_Logo.png"://    require("./../assets/crests/Cardiff_City_Logo.png"),
  "Aston_Villa_logo.svg": require("../assets/crests/Aston_Villa_logo.png"),
  "Rotherham_United_FC.svg": require("../assets/crests/Rotherham_United_FC.png"),
  "Stade_Reims_Logo.svg": require("../assets/crests/Stade_Reims_Logo.png"),
  "RC_Lens_Logo.svg": require("../assets/crests/RC_Lens_Logo.png"),
};

export default {
  IMAGES
};
